import { FC } from "react";
import styles from "./MainLayout.module.css";
import Head from "next/head";

type Props = {
    children: string | JSX.Element | JSX.Element[]
}

const MainLayout: FC<Props> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Gerson Page</title>
                <meta name="description" content="Generated by create Home Page" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {children}
            </main>
        </>
    )
}

export default MainLayout